<ul>
	<?php $mode = Request::param ('mode', Session::param('mode', 'public')); ?>
	<li <?php if (Request::actionName () == 'index' && $mode == 'public') { echo 'class="active"'; } ?>>
		<a href="<?php echo Url::display (array ('params' => array ('mode' => 'public'))); ?>"><?php echo Translate::t ('see links'); ?></a>
	</li>
	<li <?php if (Request::actionName () == 'index' && $mode == 'private') { echo 'class="active"'; } ?>>
		<a href="<?php echo Url::display (array ('params' => array ('mode' => 'private'))); ?>"><?php echo Translate::t ('only private'); ?></a>
	</li>
	<li <?php if (Request::actionName () == 'configuration') { echo 'class="active"'; } ?>>
		<a href="<?php echo Url::display (array ('a' => 'configuration')); ?>"><?php echo Translate::t ('options'); ?></a>
	</li>
</ul>
