<div id="panel">
	<div id="addPanel">
		<h2><?php echo Translate::t ('add link'); ?></h2>
		<?php if (isset ($this->retour)) { ?>
		<div class="error"><?php echo $this->retour; ?></div>
		<?php } ?>
		<form method="post" action="">
			<label for="url"><?php echo Translate::t ('url'); ?></label>
			<input type="url" name="url" id="url" />
			
			<label for="title"><?php echo Translate::t ('title'); ?></label>
			<input type="text" name="title" id="title" />
			
			<label for="description"><?php echo Translate::t ('description'); ?></label>
			<textarea name="description" id="description"></textarea>
			
			<label for="tags"><?php echo Translate::t ('tags'); ?></label>
			<input type="text" name="tags" id="tags" />
			
			<br />
			<input type="checkbox" name="private" id="private" />
			<label for="private" class="for_checkbox"><?php echo Translate::t ('private'); ?></label>
			
			<br />
			<label> </label>
			<input type="submit" value="<?php echo Translate::t ('add'); ?>" />
		</form>
	</div>
</div>
