<div id="panel">
	<div class="aside">
		<ul>
			<li class="active"><a href="">Import / Export Shaarli</a></li>
		</ul>
	</div>

	<div id="configuration">
		<form method="post" action="" enctype="multipart/form-data">
			<h2>Export Shaarli</h2>
			<button formaction="<?php echo Url::display (array ('a' => 'export')); ?>">Exporter au format Shaarli</button>
			
			<h2>Import Shaarli</h2>
			<label for="file">Fichier</label>
			<input type="file" name="file" id="file" />
			<input type="submit" value="Charger" />
		</form>
	</div>
</div>
