<div id="panel">
	<?php $links = $this->linksPaginator->items (); ?>
	<?php if (!empty ($links)) { ?>
	<div id="listLinks">
		<h2><?php echo count ($this->linksPaginator->items (true)); ?> liens</h2>
		<ul>
			<li><?php $this->linksPaginator->render ('pagination.phtml', 'page'); ?></li>
			<?php foreach ($links as $link) { ?>
			<?php $active = isset ($this->link) && $this->link->id () == $link->id (); ?>
			<li <?php if ($active) { echo 'class="active"'; } ?>>
				<a target="_blank" href="<?php echo $link->url (); ?>"><?php
				$title = $link->title ();
				if (!empty ($title)) {
					echo $link->title ();
				} else {
					echo $link->url ();
				}
				?></a>
				
				<span class="desc<?php if ($link->priv ()) { echo ' private'; } ?>">
					<?php if (!$active) { ?>
					<a href="<?php echo Url::display (array ('c' => 'link', 'a' => 'update', 'params' => array ('id' => $link->id ()))); ?>">Éditer</a> - 
					<?php } ?>
					<span class="date">le <?php echo $link->date (true); ?></span>
				<?php
				$desc = $link->description ();
				if (!empty ($desc)) {
					echo ' - ' . nl2br ($desc);
				}
				?>
				</span>
			</li>
			<?php } ?>
			<li><?php $this->linksPaginator->render ('pagination.phtml', 'page'); ?></li>
		</ul>
	</div>
	<?php } else { ?>
	<div class="nothing"><?php echo Translate::t ('no link'); ?></div>
	<?php } ?>
	
	<?php if (isset ($this->link)) { ?>
	<div class="editLink">
		<h2>Éditer un lien</h2>
		<form method="post" action="<?php echo Url::display (array ('c' => 'link', 'a' => 'update', 'params' => array ('id' => $this->link->id ()))); ?>">
			<label for="title">Titre</label>
			<input type="text" name="title" id="title" value="<?php echo $this->link->title (); ?>" />
			
			<label for="url">URL</label>
			<input type="url" name="url" id="url" value="<?php echo $this->link->url (); ?>" />
			
			<label for="desc">Description</label>
			<textarea name="desc" id="desc"><?php echo $this->link->description (); ?></textarea>
			
			<div class="checkbox_group">
				<input type="checkbox" name="private" id="private" value="private" <?php if ($this->link->priv ()) { echo 'checked="checked"'; } ?> />
				<label for="private">Privé ?</label>
			</div>
			
			<div class="checkbox_group">
				<input type="checkbox" name="upDate" id="upDate" value="upDate" />
				<label for="upDate">Mettre à jour la date</label>
			</div>
			
			<input type="submit" value="Valider" />
			<button class="delete" formaction="<?php echo Url::display (array ('c' => 'link', 'a' => 'delete', 'params' => array ('id' => $this->link->id ()))); ?>">Supprimer</button>
		</form>
	</div>
	<?php } ?>
</div>
