<div id="panel">
	<?php if (!empty ($this->links)) { ?>
	<div id="listLinks">
		<ul>
			<?php foreach ($this->links as $link) { ?>
			<li>
				<a target="_blank" href="<?php echo $link->url (); ?>"><?php
				$title = $link->title ();
				if (!empty ($title)) {
					echo $link->title ();
				} else {
					echo $link->url ();
				}
				?></a>
				
				<?php
				$desc = $link->description ();
				if (!empty ($desc)) {
					echo '<span class="desc">' . $desc . '</span>';
				}
				?>
			</li>
			<?php } ?>
		</ul>
	</div>
	<?php } else { ?>
	<div class="nothing"><?php echo Translate::t ('no link'); ?></div>
	<?php } ?>
</div>
