<?php
	$c = Request::controllerName ();
	$a = Request::actionName ();
	$params = Request::params ();
?>

<span class="pagination">
<?php if ($this->currentPage > 1) { ?>
<?php $params[$getteur] = $this->currentPage - 1; ?>
<a class="pager-previous" href="<?php echo Url::display (array ('c' => $c, 'a' => $a, 'params' => $params)); ?>">‹ Précédent</a>
<?php } ?>

<span class="current-page">page <?php echo $this->currentPage; ?> / <?php echo $this->nbPage; ?></span>

<?php if ($this->currentPage < $this->nbPage) { ?>
<?php $params[$getteur] = $this->currentPage + 1; ?>
<a class="pager-next" href="<?php echo Url::display (array ('c' => $c, 'a' => $a, 'params' => $params)); ?>">Suivant ›</a>
<?php } ?>
</span>
